Prevent rollbar-java's log.error() calls from triggering new rollbar reports
Rollbar-java now has internal slf4j logging that can be picked up by red-egg's appender-based collectors.
This caused a feedback loop in EP.
I am guessing we hit a rate limit, for unrelated reasons, and then once that happened,
error message logged by com.rollbar.notifier.sender.SyncSender started the loop.

The stack trace looked like this:
com.rollbar.notifier.sender.exception.SenderException: com.rollbar.notifier.sender.exception.ApiException: Over rate limit. Access token e5d1<removed>.
	at com.rollbar.notifier.sender.AbstractSender.send(AbstractSender.java:44)
	at org.cru.redegg.reporting.rollbar.RollbarReporter.send(RollbarReporter.java:49)
	at org.cru.redegg.reporting.InMemoryErrorQueue.run(InMemoryErrorQueue.java:128)
	at java.util.concurrent.Executors.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.rollbar.notifier.sender.exception.ApiException: Over rate limit. Access token e5d1336b7f9247b18ebe799a2cd445b3.
	at com.rollbar.notifier.sender.AbstractSender.send(AbstractSender.java:39)
	... 7 common frames omitted

This commit fixes the problem by ignoring that logger, specifically, and the other loggers
that I manually found in rollbar-java's source code that call logger.error().

I would have preferred to change the 'ignoredLoggers' semantics to 'starts-with' instead of 'equals',
and then have a single 'org.rollbar.' value in the set,
but that looked like an involved implementation task,
and I just want to get this out to break the loop in EP.